<?php



function form_example_block_info(){
	$blocks['bloque_form_example'] = array(
		// Título del bloque en la configuración del administrador
		'info' => t('Bloque form'),
		'cache' => DRUPAL_NO_CACHE,
	);

	return $blocks;
}


function form_example_block_view($delta = '') {
    $block = array();
  	switch ($delta) {
	    case 'bloque_form_example':
	      // Título del bloque.
	      $block['subject'] = t('Bloque prueba');
	      // Función que retorna el contenido o función que se quiere en el bloque.
	      $block['content'] = drupal_get_form('form_example_form');
	      break;
    }
    dpm($block);
    return $block;
}
  
	
function form_example_form($form, &$form_state) {
	  $form['text_nombre'] = array(
	    '#type' => 'textfield',
	    '#title' => 'nombre',
	    '#required' => TRUE,
	  );
	   $form['text_pass'] = array(
	    '#type' => 'textfield',
	    '#title' => 'contraseña',
	    '#required' => TRUE,
	  );
	  $form['submit_button'] = array(
	    '#type' => 'submit',
	    '#value' => t('Click Here!'),
	  ); 
  return $form;
}


function form_example_menu() {
  $items = array();

  $items['custom/form-example'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Example Form', //page title
    'description' => 'A form to mess around with.',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('form_example_form'), //put the name of the form here
    'access callback' => TRUE
  );
  
  return $items;
}

function form_example_form_validate($form, &$form_state) {
  if (!($form_state['values']['text_nombre'] = "")){
    form_set_error('text_nombre', t('Debe llenar el nombre.'));
  } elseif(!($form_state['values']['text_pass'] = "")){
  	form_set_error('text_pass', t('Debe llenar la contraseña.'));
  }
  	  $form['nodo1'] = nodo_prueba();
}

function nodo_prueba(){

    $body_text = 'This is the body text I want entered with the node.';
 	$node = new stdClass();
 	$node->type = 'article';
  	node_object_prepare($node);
  	$node->title    = 'Node Created Programmatically on ' . date('c');
  	$node->language = LANGUAGE_NONE;
    $node->body[$node->language][0]['value']   = $body_text;
    $node->body[$node->language][0]['summary'] = text_summary($body_text);
  	$node->body[$node->language][0]['format']  = 'filtered_html';
  	$path = 'content/programmatically_created_node_' . date('YmdHis');
  	$node->path = array('alias' => $path);
    node_save($node);
}